[package]
name = "frame-benchmarking-freestanding-cli"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Freestanding CLI for benchmarking FRAME pallets."

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-runtime = { path = "../../../../primitives/runtime" }
clap = { version = "4.5.1", features = ["derive"] }
frame-benchmarking-cli = { path = "../" }
sc-cli = { path = "../../../../client/cli" }

# optional host functions
sp-statement-store = { path = "../../../../primitives/statement-store", optional = true }
env_logger = "0.11.2"
log.workspace = true

[features]
default = [ "extended-host-functions" ]
extended-host-functions = [ "dep:sp-statement-store" ]
